--TABLES 

DROP TABLE ATHLETE CASCADE CONSTRAINTS;
DROP TABLE ATHLETE_FANZONE CASCADE CONSTRAINTS;
DROP TABLE COACH CASCADE CONSTRAINTS;
DROP TABLE COUNTRIES CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE EVENT_NEWS CASCADE CONSTRAINTS;
DROP TABLE FANZONE CASCADE CONSTRAINTS;
DROP TABLE MEDALS CASCADE CONSTRAINTS;
DROP TABLE NEWSANDVIDEOS CASCADE CONSTRAINTS;
DROP TABLE TEAMS CASCADE CONSTRAINTS;

--CREATE TABLES

CREATE TABLE ATHLETE (
    ATHLETE_ID         NUMBER(10) NOT NULL,
    ATHLETE_FILE_LOB   BLOB,
    FIRST_NAME         VARCHAR2(30),
    LAST_NAME          VARCHAR2(30) NOT NULL,
    AGE                NUMBER(2) NOT NULL,
    HEIGHT             NUMBER(3, 2) NOT NULL,
    WEIGHT             NUMBER(5, 2) NOT NULL,
    GENDER             VARCHAR2(1) NOT NULL,
    MARITIAL_STATUS    VARCHAR2(1),
    COUNTRY_ID         VARCHAR2(10) NOT NULL,
    COACH_ID           NUMBER(10) NOT NULL,
    EVENT_ID           NUMBER(10) NOT NULL,
    TEAM_ID            NUMBER(10),
    RANK_POINT         NUMBER(5, 2) NOT NULL,
    COACHING_DURATION  NUMBER(3, 1)
);

ALTER TABLE ATHLETE ADD CONSTRAINT ATHLETE_PK PRIMARY KEY ( ATHLETE_ID );

CREATE TABLE ATHLETE_FANZONE (
    ATHLETE_ID         NUMBER(10) NOT NULL,
    FAN_ID             NUMBER(15) NOT NULL,
    STARTED_FOLLOWING  DATE
);

ALTER TABLE ATHLETE_FANZONE ADD CONSTRAINT ATHLETE_FANZONE_PK PRIMARY KEY ( ATHLETE_ID,
                                                                            FAN_ID );

CREATE TABLE COACH (
    COACH_ID             NUMBER(10) NOT NULL,
    FIRST_NAME           VARCHAR2(30),
    LAST_NAME            VARCHAR2(30) NOT NULL,
    COACHING_COUNTRY_ID  VARCHAR2(10) NOT NULL,
    COACHING_CAREER      NUMBER(3, 1)
);

ALTER TABLE COACH ADD CONSTRAINT COACH_PK PRIMARY KEY ( COACH_ID );

CREATE TABLE COUNTRIES (
    COUNTRY_FILE_LOB  BLOB,
    COUNTRY_ID        VARCHAR2(10) NOT NULL,
    COUNTRY_NAME      VARCHAR2(56) NOT NULL,
    REGION            VARCHAR2(20)
);

ALTER TABLE COUNTRIES ADD CONSTRAINT COUNTRIES_PK PRIMARY KEY ( COUNTRY_ID );

CREATE TABLE EVENT (
    EVENT_ID        NUMBER(10) NOT NULL,
    EVENT_FILE_LOB  BLOB,
    EVENT_NAME      VARCHAR2(100) NOT NULL,
    EVENT_TYPE      VARCHAR2(100) NOT NULL,
    EVENT_DATE      DATE NOT NULL,
    LOCATION        VARCHAR2(100) NOT NULL,
    BUDGET          NUMBER(10, 2)
);

ALTER TABLE EVENT ADD CONSTRAINT EVENT_PK PRIMARY KEY ( EVENT_ID );

CREATE TABLE EVENT_NEWS (
    EVENT_ID       NUMBER(10) NOT NULL,
    NEWS_ID        NUMBER(30) NOT NULL,
    NEWS_DATE      DATE,
    ICONIC_MOMENT  VARCHAR2(500)
);

ALTER TABLE EVENT_NEWS ADD CONSTRAINT EVENT_NEWS_PK PRIMARY KEY ( EVENT_ID,
                                                                  NEWS_ID );

CREATE TABLE FANZONE (
    FAN_ID      NUMBER(15) NOT NULL,
    FIRST_NAME  VARCHAR2(30),
    LAST_NAME   VARCHAR2(30) NOT NULL,
    AGE         NUMBER(3, 1) NOT NULL,
    COUNTRY_ID  VARCHAR2(10) NOT NULL
);

ALTER TABLE FANZONE ADD CONSTRAINT FANZONE_PK PRIMARY KEY ( FAN_ID );

CREATE TABLE MEDALS (
    ATHLETE_ID  NUMBER(10) NOT NULL,
    MEDAL_NAME  VARCHAR2(6) NOT NULL
);

ALTER TABLE MEDALS ADD CONSTRAINT MEDALS_PK PRIMARY KEY ( ATHLETE_ID );

CREATE TABLE NEWSANDVIDEOS (
    NEWS_ID        NUMBER(10) NOT NULL,
    NEWS_FILE_LOB  BLOB,
    NEWS_LINK      VARCHAR2(100),
    COPYRIGHT      VARCHAR2(30)
);

ALTER TABLE NEWSANDVIDEOS ADD CONSTRAINT NEWSANDVIDEOS_PK PRIMARY KEY ( NEWS_ID );

CREATE TABLE TEAMS (
    TEAM_ID     NUMBER(10) NOT NULL,
    COUNTRY_ID  VARCHAR2(10) NOT NULL,
    EVENT_ID    NUMBER(10) NOT NULL,
    COACH_ID    NUMBER(10) NOT NULL
);

CREATE UNIQUE INDEX TEAMS__IDX ON
    TEAMS (
        COACH_ID
    ASC );

ALTER TABLE TEAMS ADD CONSTRAINT TEAMS_PK PRIMARY KEY ( TEAM_ID );

ALTER TABLE ATHLETE
    ADD CONSTRAINT ATHLETE_COACH_FK FOREIGN KEY ( COACH_ID )
        REFERENCES COACH ( COACH_ID );

ALTER TABLE ATHLETE
    ADD CONSTRAINT ATHLETE_COUNTRIES_FK FOREIGN KEY ( COUNTRY_ID )
        REFERENCES COUNTRIES ( COUNTRY_ID );

ALTER TABLE ATHLETE
    ADD CONSTRAINT ATHLETE_EVENT_FK FOREIGN KEY ( EVENT_ID )
        REFERENCES EVENT ( EVENT_ID );

ALTER TABLE ATHLETE_FANZONE
    ADD CONSTRAINT ATHLETE_FANZONE_ATHLETE_FK FOREIGN KEY ( ATHLETE_ID )
        REFERENCES ATHLETE ( ATHLETE_ID )
            ON DELETE CASCADE;

ALTER TABLE ATHLETE_FANZONE
    ADD CONSTRAINT ATHLETE_FANZONE_FANZONE_FK FOREIGN KEY ( FAN_ID )
        REFERENCES FANZONE ( FAN_ID )
            ON DELETE CASCADE;

ALTER TABLE ATHLETE
    ADD CONSTRAINT ATHLETE_TEAMS_FK FOREIGN KEY ( TEAM_ID )
        REFERENCES TEAMS ( TEAM_ID );

ALTER TABLE COACH
    ADD CONSTRAINT COACH_COUNTRIES_FK FOREIGN KEY ( COACHING_COUNTRY_ID )
        REFERENCES COUNTRIES ( COUNTRY_ID );

ALTER TABLE EVENT_NEWS
    ADD CONSTRAINT EVENT_NEWS_EVENT_FK FOREIGN KEY ( EVENT_ID )
        REFERENCES EVENT ( EVENT_ID )
            ON DELETE CASCADE;

ALTER TABLE EVENT_NEWS
    ADD CONSTRAINT EVENT_NEWS_NEWSANDVIDEOS_FK FOREIGN KEY ( NEWS_ID )
        REFERENCES NEWSANDVIDEOS ( NEWS_ID )
            ON DELETE CASCADE;

ALTER TABLE FANZONE
    ADD CONSTRAINT FANZONE_COUNTRIES_FK FOREIGN KEY ( COUNTRY_ID )
        REFERENCES COUNTRIES ( COUNTRY_ID );

ALTER TABLE MEDALS
    ADD CONSTRAINT MEDALS_ATHLETE_FK FOREIGN KEY ( ATHLETE_ID )
        REFERENCES ATHLETE ( ATHLETE_ID );

ALTER TABLE TEAMS
    ADD CONSTRAINT TEAMS_COACH_FK FOREIGN KEY ( COACH_ID )
        REFERENCES COACH ( COACH_ID );

ALTER TABLE TEAMS
    ADD CONSTRAINT TEAMS_COUNTRIES_FK FOREIGN KEY ( COUNTRY_ID )
        REFERENCES COUNTRIES ( COUNTRY_ID );

ALTER TABLE TEAMS
    ADD CONSTRAINT TEAMS_EVENT_FK FOREIGN KEY ( EVENT_ID )
        REFERENCES EVENT ( EVENT_ID );

--INSERT DATABASE

--INSERT INTO EVENT VALUES(20, 'Archery', 'Single', 'JUN-01-2020', 'Yumenoshima Park Archery Field', 99);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(500, '3x3 Basketball', '8-team tournament', 'JUl-24 -2020', 'Aomi Urban Sports Park', 32000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(501, 'Archery', 'Individual competition (Men/Women)', 'JUl-29-2020', 'Yumenoshima Park Archery Field', 32000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(502, 'Archery', 'Team competition (Men/Women)', 'JUl-30-2020', 'Yumenoshima Park Archery Field', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(503, 'Archery', 'Mixed Team', 'JUl-31-2020', 'Yumenoshima Park Archery Field', 99);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(504, 'Artistic Gymnastics', 'Team competition (Men/Women)', 'JUl-24-2020', 'Ariake Gymnastics Centre',56000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(505, 'Artistic Gymnastics', 'Individual all-around competition (Men/Women)', 'JUl-25-2020', 'Ariake Gymnastics Centre', 50000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(506, 'Artistic Gymnastics', 'Floor exercise (Men)', 'JUl-25-2020', 'Ariake Gymnastics Centre', 55000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(507, 'Artistic Gymnastics', 'Floor exercise (Women)', 'JUl-25-2020', 'Ariake Gymnastics Centre', 55000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(508, 'Artistic Gymnastics', 'Pommel horse (Men)', 'JUl-26-2020', 'Ariake Gymnastics Centre', 55000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(509, 'Artistic Gymnastics', 'Uneven bars (Women', 'JUl-27-2020', 'Ariake Gymnastics Centre', 55000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(510, 'Artistic Gymnastics', 'Rings (Men)', 'JUl-28-2020', 'Ariake Gymnastics Centre',55000 );
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(511, 'Artistic Gymnastics', 'Balance Beam (Women)', 'JUl-29-2020', 'Ariake Gymnastics Centre', 55000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(512, 'Artistic Gymnastics', 'Rings (Men)', 'JUl-29-2020', 'Ariake Gymnastics Centre', 55000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(513, 'Artistic Gymnastics', 'Vault (Men)', 'AUG-01-2020', 'Ariake Gymnastics Centre',55000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(514, 'Artistic Gymnastics', 'Vault (Women)', 'AUG-01-2020', 'Ariake Gymnastics Centre',55000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(515, 'Artistic Swimming', 'Duets (Women)', 'AUG-02-2020', 'Tokyo Aquatics Centre',42000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(516, 'Artistic Swimming', 'Teams (Women)', 'AUG-03-2020', 'Tokyo Aquatics Centre',42000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(517, 'Athletics', '100m (Women)', 'AUG-04-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(518, 'Athletics', '200m (Men)', 'AUG-04-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(519, 'Athletics', '400m (Women)', 'AUG-04-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(520, 'Athletics', '800m (Men)', 'AUG-04-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(521, 'Athletics', '1,500m (Men)', 'AUG-05-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(522, 'Athletics', '5,000m (Women)', 'AUG-05-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(523, 'Athletics', '10,000m (Men)', 'AUG-05-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(524, 'Athletics', '110m Hurdles (Men)', 'AUG-05-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(525, 'Athletics', '100m Hurdles (Women)', 'AUG-04-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(526, 'Athletics', '400m Hurdles (Men)', 'AUG-04-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(527, 'Athletics', '3,000m Steeplechase (Women)', 'AUG-04-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(528, 'Athletics', '4 x 100m Relay (Men)', 'AUG-06-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(529, 'Athletics', '4 x 400m Relay (Men)', 'AUG-07-2020', 'Olympic Stadium', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(530, 'Athletics', '4 x 400m Mixed Relay', 'AUG-08-2020', 'Olympic Stadium', 35000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(531, 'Badminton', 'Singles (Men)', 'JUL-30-2021', 'Musashino Forest Sport Plaza BDM Court 1', 33000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(532, 'Badminton', 'Singles (Women)', 'JUL-30-2021', 'Musashino Forest Sport Plaza BDM Court 1', 33000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(533, 'Badminton', 'Doubles (Men)', 'JUL-29-2021', 'Musashino Forest Sport Plaza BDM Court 2', 33000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(534, 'Badminton', 'Doubles (Women)', 'JUL-29-2021', 'Musashino Forest Sport Plaza BDM Court 2', 33000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(535, 'Badminton', 'Mixed Doubles', 'Aug-01-2021', 'Musashino Forest Sport Plaza BDM Court 3', 33000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(536, 'Baseball/Softball', 'Baseball (Men)', 'AUG-03-2021', 'Fukushima Azuma Baseball Stadium', 43000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(537, 'Basketball', '12-team tournament (Men)', 'AUG-05-2021', 'Saitama Super Arena', 38000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(538, 'Basketball', '12-team tournament (Women)', 'AUG-04-2021', 'Saitama Super Arena', 38000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(539, 'Beach Volleyball', '24-team tournament (Men)', 'AUG-03-2021', 'Shiokaze Park - Centre Court', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(540, 'Beach Volleyball', '24-team tournament (Women)', 'AUG-03-2021', 'Shiokaze Park - Centre Court', 40000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(541, 'Boxing', 'Fly (48-52kg)(Men)', 'AUG-04-2021', 'Kokugikan Arena', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(542, 'Boxing', 'Feather (52-57kg)(Men)', 'AUG-04-2021', 'Kokugikan Arena', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(543, 'Boxing', 'Light (57-63kg)(Men)', 'AUG-05-2021', 'Kokugikan Arena', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(544, 'Boxing', 'Welter (63-69kg)(Men)', 'AUG-05-2021', 'Kokugikan Arena', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(545, 'Boxing', 'Middle (69-75kg)(Men)', 'AUG-06-2021', 'Kokugikan Arena', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(546, 'Boxing', 'Light Heavy (75-81kg)(Men)', 'AUG-06-2021', 'Kokugikan Arena', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(547, 'Boxing', 'Heavy (81-91kg)(Men)', 'AUG-07-2021', 'Kokugikan Arena', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(548, 'Boxing', 'Super Heavy (+91kg)(Men)', 'AUG-08-2021', 'Kokugikan Arena', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(549, 'Boxing', 'Fly (48-51kg)(Women)', 'AUG-04-2021', 'Kokugikan Arena', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(550, 'Boxing', 'Feather (54-57kg)(Women)', 'AUG-04-2021', 'Kokugikan Arena', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(551, 'Boxing', 'Light (57-60kg)(Women)', 'AUG-04-2021', 'Kokugikan Arena', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(552, 'Boxing', 'Welter (64-69kg)(Women)', 'AUG-04-2021', 'Kokugikan Arena', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(553, 'Boxing', 'Middle (69-75kg)(Women)', 'AUG-04-2021', 'Kokugikan Arena', 35000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(554, 'Canoe Slalom', 'Kayak (K-1) (Men)', 'JUL-27-2021', 'Kasai Canoe Slalom Centre', 30000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(555, 'Canoe Slalom', 'Kayak (K-1) (Women)', 'JUL-27-2021', 'Kasai Canoe Slalom Centre', 30000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(556, 'Canoe Slalom', 'Canoe (C-1) (Men)', 'JUL-29-2021', 'Kasai Canoe Slalom Centre', 30000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(557, 'Canoe Slalom', 'Canoe (C-1) (Women)', 'JUL-29-2021', 'Kasai Canoe Slalom Centre', 30000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(558, 'Canoe Sprint', 'Kayak Single (K-1) 200m (Men)', 'AUG-02-2021', 'Sea Forest Waterway', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(559, 'Canoe Sprint', 'Kayak Single (K-1) 200m (Women)', 'AUG-02-2021', 'Sea Forest Waterway', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(560, 'Canoe Sprint', 'Kayak Four (K-4) 500m (Men)', 'AUG-05-2021', 'Sea Forest Waterway', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(561, 'Canoe Sprint', 'Kayak Four (K-4) 500m (Women)', 'AUG-05-2021', 'Sea Forest Waterway', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(562, 'Canoe Sprint', 'Canoe Single (C-1) 1,000m (Men)', 'AUG-06-2021', 'Sea Forest Waterway', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(563, 'Canoe Sprint', 'Canoe Single (C-1) 1,000m (Women)', 'AUG-06-2021', 'Sea Forest Waterway', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(564, 'Canoe Sprint', 'Canoe Double (C-2) 1,000m (Men)', 'AUG-07-2021', 'Sea Forest Waterway', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(565, 'Canoe Sprint', 'Canoe Double (C-2) 1,000m (Women)', 'AUG-07-2021', 'Sea Forest Waterway', 35000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(566, 'Cycling BMX Freestyle', 'Park (Men)', 'FEB-18-2020', 'Ariake Sports Park BMX Freestyle', 70000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(567, 'Cycling BMX Racing', 'Race (Men)', 'FEB-18-2020', 'Ariake Urban Sports Park', 80000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(568, 'Cycle Mountain Bike', 'Cross-Country (Men)', 'FEB-18-2020', 'Izu MTB Course', 99000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(569, 'Cycle Road', 'Road Race (Men)', 'FEB-18-2020', 'Fuji International Speedway', 85000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(570, 'Cycle Road', 'Individual Time Trial (Men)', 'FEB-18-2020', 'Fuji International Speedway', 85000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(571, 'Cycling Track', 'Team Sprint (Men)', 'AUG-04-2021', 'Izu Velodrome', 65000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(572, 'Cycling Track', 'Sprint (Men)', 'AUG-04-2021', 'Izu Velodrome', 65000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(573, 'Cycling Track', 'Keirine (Men)', 'AUG-05-2021', 'Izu Velodrome', 65000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(574, 'Cycling Track', 'Team Pursuit (Men)', 'AUG-06-2021', 'Izu Velodrome', 65000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(575, 'Cycling Track', 'Omnium (Men)', 'AUG-07-2021', 'Izu Velodrome', 65000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(576, 'Cycling Track', 'Madison (Men)', 'AUG-08-2021', 'Izu Velodrome', 65000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(577, 'Diving', '3m Springboard (Men)', 'AUG-03-2021', 'Tokyo Aquatics Centre', 70000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(578, 'Diving', '10m Platform (Men)', 'AUG-04-2021', 'Tokyo Aquatics Centre', 70000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(579, 'Diving', 'Synchronised 3m Springboard (Men)', 'AUG-05-2021', 'Tokyo Aquatics Centre', 70000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(580, 'Diving', 'Synchronised 10m Platform (Men)', 'AUG-06-2021', 'Tokyo Aquatics Centre', 70000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(581, 'Equestrian', 'Dressage (Men)', 'AUG-03-2021', 'Equestrian Park', 95000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(582, 'Equestrian', 'Jumping (Men)', 'AUG-06-2021', 'Equestrian Park', 95000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(583, 'Equestrian', 'Eventinge (Men)', 'AUG-07-2021', 'Equestrian Park', 95000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(584, 'Fencing', 'Individual Foil (Men)', 'JUL-28-2021', 'Makuhari Messe Hall B Blue Piste', 60000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(585, 'Fencing', 'Individual Epée (Men)', 'JUL-28-2021', 'Makuhari Messe Hall B Red Piste', 60000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(586, 'Fencing', 'Individual Sabre (Men)', 'JUL-29-2021', 'Makuhari Messe Hall B Green Piste', 60000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(587, 'Fencing', 'Team Foil (Men)', 'JUL-29-2021', 'Makuhari Messe Hall B Yellow Piste', 60000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(588, 'Fencing', 'Team Epée (Men)', 'JUL-30-2021', 'Makuhari Messe Hall B Blue Piste', 60000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(589, 'Fencing', 'Team Sabre (Men)', 'JUL-31-2021', 'Makuhari Messe Hall B Green Piste', 60000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(590, 'Football', '16-team tournament (Men)', 'AUG-02-2021', 'Sapporo Dome', 99000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(591, 'Football', '16-team tournament (Women)', 'AUG-02-2021', 'Sapporo Dome', 99000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(592, 'Football', '12-team tournament (Men)', 'AUG-06-2021', 'Tokyo Stadium', 99000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(593, 'Football', '12-team tournament (Women)', 'AUG-06-2021', 'Tokyo Stadium', 99000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(594, 'Golf', 'Individual Stroke Play (Men)', 'AUG-01-2021', 'Kasumigaseki Country Club', 98000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(595, 'Golf', 'Individual Stroke Play (Women)', 'AUG-01-2021', 'Kasumigaseki Country Club', 98000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(596, 'Handball', '12-team tournament (Men)', 'AUG-04-2021', 'Yoyogi National Stadium', 48000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(597, 'Handball', '12-team tournament (Women)', 'AUG-04-2021', 'Yoyogi National Stadium', 48000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(598, 'Hockey', '12-team tournament (Men)', 'AUG-02-2021', 'Oi Hockey Stadium', 66000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(599, 'Hockey', '12-team tournament (Women)', 'AUG-02-2021', 'Oi Hockey Stadium', 66000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(600, 'Judo', '- 60kg (Men)', 'JUL-27-2021', 'Nippon Budokan Judo Mat 1', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(601, 'Judo', '- 66kg (Men)', 'JUL-27-2021', 'Nippon Budokan Judo Mat 1', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(602, 'Judo', '- 73kg (Men)', 'JUL-28-2021', 'Nippon Budokan Judo Mat 2', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(603, 'Judo', '- 81kg (Men)', 'JUL-28-2021', 'Nippon Budokan Judo Mat 1', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(604, 'Judo', '- 90kg (Men)', 'JUL-28-2021', 'Nippon Budokan Judo Mat 1', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(605, 'Judo', '- 100kg (Men)', 'JUL-28-2021', 'Nippon Budokan Judo Mat 2', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(606, 'Judo', '+ 100kg (Men)', 'JUL-29-2021', 'Nippon Budokan Judo Mat 1', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(607, 'Judo', '- 48kg (Women)', 'JUL-29-2021', 'Nippon Budokan Judo Mat 1', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(608, 'Judo', '- 52kg (Women)', 'JUL-29-2021', 'Nippon Budokan Judo Mat 2', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(609, 'Judo', '- 57kg (Women))', 'JUL-29-2021', 'Nippon Budokan Judo Mat 1', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(610, 'Judo', '- 63kg (Women)', 'JUL-29-2021', 'Nippon Budokan Judo Mat 2', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(611, 'Judo', '- 70kg (Women)', 'JUL-30-2021', 'Nippon Budokan Judo Mat 1', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(612, 'Judo', '- 78kg (Women)', 'JUL-30-2021', 'Nippon Budokan Judo Mat 2', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(613, 'Judo', '+ 78kg (Women)', 'JUL-31-2021', 'Nippon Budokan Judo Mat 2', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(614, 'Judo', 'Mixed Team', 'JUL-31-2021', 'Nippon Budokan Judo Mat 1', 40000);



INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(615, 'Karate', 'Kata (Men)', 'FEB-18-2020', 'Nippon Budokan Judo Mat 1', 50000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(616, 'Karate', 'Kata (Women)', 'FEB-18-2020', 'Nippon Budokan Judo Mat 1', 50000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(617, 'Karate', 'Kumite (Men/Women)', 'JUN-17-2020', 'Nippon Budokan Judo Mat 2', 50000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(618, 'Karate', 'Kumite (Men/Women)', 'JUN-17-2020', 'Nippon Budokan Judo Mat 2', 50000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(619, 'Karate', 'Three weight categories (Men -67kg, -75kg, +75kg)', 'AUG-06-2021', 'Nippon Budokan Judo Mat 1', 50000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(620, 'Karate', 'Three weight categories (Women -55kg, -61kg, +61kg)', 'AUG-07-2021', 'Nippon Budokan Judo Mat 1', 50000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(621, 'Marathon Swimming', '10km Marathon Swimming (Men)', 'FEB-18-2020', 'Odaiba Marine Park', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(622, 'Marathon Swimming', '10km Marathon Swimming (Women)', 'AUG-04-2021', 'Odaiba Marine Park', 35000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(623, 'Modern Pentathlon', 'Individual competition (Men)', 'FEB-18-2020', 'Musashino Forest Sport Plaza', 40000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(624, 'Modern Pentathlon', 'Individual competition (Women)', 'AUG-06-2021', 'Tokyo Stadium', 40000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(625, 'Rhythmic Gymnastics', 'Individual all-around competition (Women)', 'DEC-20-2020', 'Ariake Gymnastics Centre',41000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(626, 'Rhythmic Gymnastics', 'Group all-around competition (Women))', 'MAY-09-2021', 'Ariake Gymnastics Centre',41000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(627, 'Rowing', 'Single Sculls (1x) (Men)', 'JUN-23-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(628, 'Rowing', 'Single Sculls (1x) (Women)', 'JUN-23-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(629, 'Rowing', 'Pair (2-) (Men)', 'JUN-23-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(630, 'Rowing', 'Pair (2-) (Women)', 'JUN-23-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(631, 'Rowing', 'Double Sculls (2x) (Men)', 'JUN-28-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(632, 'Rowing', 'Double Sculls (2x) (Women)', 'JUN-28-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(633, 'Rowing', 'Four (4-) (Men)', 'JUN-28-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(634, 'Rowing', 'Four (4-) (Women)', 'JUN-28-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(635, 'Rowing', 'Quadruple Sculls (4x) (Men)', 'JUN-29-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(636, 'Rowing', 'Quadruple Sculls (4x) (Women)', 'JUN-29-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(637, 'Rowing', 'Eight (8+) (Men)', 'JUN-29-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(638, 'Rowing', 'Eight (8+) (Women)', 'JUN-29-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(639, 'Rowing', 'Lightweight Double Sculls (2x) (Men)', 'JUN-30-2021', 'Sea Forest Waterway', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(640, 'Rowing', 'Lightweight Double Sculls (2x) (Women)', 'JUN-30-2021', 'Sea Forest Waterway', 45000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(641, 'Rugby', '12-team tournament (Men)', 'JUL-27-2021', 'Tokyo Stadium', 44000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(642, 'Rugby', '12-team tournament (Women)', 'JUL-30-2021', 'Tokyo Stadium', 44000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(643, 'Sailing', 'RS:X - Windsurfer (Men)', 'JUL-30-2021', 'Enoshima', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(644, 'Sailing', 'RS:X - Windsurfer (Women)', 'JUL-30-2021', 'Enoshima', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(645, 'Sailing', 'Laser - One Person Dinghy (Men)', 'JUL-31-2021', 'Enoshima', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(646, 'Sailing', 'Laser Radial - One Person Dinghy (Women)', 'JUL-31-2021', 'Enoshima', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(647, 'Sailing', 'Finn - One Person Dinghy (Heavyweight) (Men)', 'AUG-01-2021', 'Enoshima', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(648, 'Sailing', '470 - Two Person Dinghy (Men)', 'AUG-30-2021', 'Enoshima', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(649, 'Sailing', '470 - Two Person Dinghy (Women)', 'AUG-03-2021', 'Enoshima', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(650, 'Sailing', '49er - Skiff (Men)', 'AUG-03-2021', 'Enoshima', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(651, 'Sailing', '49er FX - Skiff (Women)', 'AUG-04-2021', 'Enoshima', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(652, 'Sailing', 'Nacra 17 Foiling - Mixed Multihull', 'AUG-04-2021', 'Enoshima', 45000);


INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(653, 'Shooting', '50m Rifle 3 Positions (Men)', 'JUL-29-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(654, 'Shooting', '50m Rifle 3 Positions (Women)', 'JUL-29-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(655, 'Shooting', '10m Air Rifle (Men)', 'JUL-29-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(656, 'Shooting', '10m Air Rifle (Women)', 'JUL-29-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(657, 'Shooting', '25m Rapid Fire Pistol (Men)', 'JUL-29-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(658, 'Shooting', '25m Pistol (Women)', 'JUL-30-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(659, 'Shooting', '10m Air Pistol (Men)', 'JUL-30-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(660, 'Shooting', '10m Air Pistol (Women)', 'JUL-30-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(661, 'Shooting', 'Trap (Men)', 'JUL-31-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(662, 'Shooting', 'Trap (Women)', 'JUL-31-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(663, 'Shooting', 'Skeet (Men)', 'JUL-31-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(664, 'Shooting', 'Skeet (Women)', 'AUG-01-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(665, 'Shooting', '10m Air Rifle Mixed Team', 'AUG-01-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(666, 'Shooting', '10m Air Pistol Mixed Team', 'AUG-02-2021', 'Asaka Shooting Range', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(667, 'Shooting', 'Trap Mixed Team', 'AUG-02-2021', 'Asaka Shooting Range', 35000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(668, 'Skateboarding', 'Park (Men)', 'JUL-25-2021', 'Ariake Sports Park Skateboarding', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(669, 'Skateboarding', 'Park (Women)', 'JUL-27-2021', 'Ariake Sports Park Skateboarding', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(670, 'Skateboarding', 'Street (Men)', 'AUG-04-2021', 'Ariake Sports Park Skateboarding', 35000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(671, 'Skateboarding', 'Street (Women)', 'AUG-05-2021', 'Ariake Sports Park Skateboarding', 35000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(672, 'Sport Climbing', 'Combined (Men)', 'FEB-19-2020', 'Aomi Urban Sports Park', 38000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(673, 'Sport Climbing', 'Combined (Women)', 'AUG-04-2021', 'Aomi Urban Sports Park', 38000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(673, 'Surfing', 'Men', 'FEB-19-2020', 'Tsurigasaki Surfing Beach', 37000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(674, 'Surfing', 'Women', 'JUL-27-2021', 'Tsurigasaki Surfing Beach', 37000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(675, 'Swimming', '100m Freestyle (Men)', 'JUL-28-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(676, 'Swimming', '100m Freestyle (Women)', 'JUL-28-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(677, 'Swimming', '400m Freestyle (Men)', 'JUL-28-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(678, 'Swimming', '400m Freestyle (Women)', 'JUL-28-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(679, 'Swimming', '1500m Freestyle (Men)', 'JUL-28-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(680, 'Swimming', '1500m Freestyle (Women)', 'JUL-29-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(681, 'Swimming', '200m Backstroke (Men)', 'JUL-29-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(682, 'Swimming', '200m Backstroke (Women)', 'JUL-29-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(683, 'Swimming', '200m Breaststroke (Men)', 'JUL-29-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(684, 'Swimming', '200m Breaststroke (Women)', 'JUL-29-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(685, 'Swimming', '200m Butterfly (Men)', 'JUL-30-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(686, 'Swimming', '200m Butterfly (Women)', 'JUL-30-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(687, 'Swimming', '400m Individual Medley (Men)', 'JUL-30-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(688, 'Swimming', '400m Individual Medley (Women)', 'JUL-31-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(689, 'Swimming', '4 x 100m Freestyle Relay (Men)', 'JUL-31-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(690, 'Swimming', '4 x 100m Freestyle Relay (Women)', 'AUG-01-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(691, 'Swimming', '4 x 100m Medley Relay (Men)', 'AUG-01-2021', 'Tokyo Aquatics Centre', 45000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(692, 'Swimming', '4 x 100m Medley Relay (Women)', 'AUG-01-2021', 'Tokyo Aquatics Centre', 45000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(693, 'Table Tennis', 'Singles (Menn)', 'AUG-02-2021', 'Tokyo Metropolitan Gymnasium Table 1', 55000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(694, 'Table Tennis', 'Singles (Women)', 'AUG-02-2021', 'Tokyo Metropolitan Gymnasium Table 2', 55000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(695, 'Table Tennis', 'Team (Men)', 'AUG-03-2021', 'Tokyo Metropolitan Gymnasium Table 1', 55000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(696, 'Table Tennis', 'Team (Women)', 'AUG-04-2021', 'Tokyo Metropolitan Gymnasium Table 2', 55000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(697, 'Table Tennis', 'Mixed Doubles', 'AUG-06-2021', 'Tokyo Metropolitan Gymnasium Table 1', 55000);

INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(698, 'Taekwondo', 'Men -58kg', 'FEB-19-2020', 'Makuhari Messe Hall A', 38000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(699, 'Taekwondo', 'Men -68kg', 'FEB-19-2020', 'Makuhari Messe Hall A', 38000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(700, 'Taekwondo', 'Men -80kg', 'FEB-19-2020', 'Makuhari Messe Hall A', 38000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(701, 'Taekwondo', 'Men +80kg', 'FEB-19-2020', 'Makuhari Messe Hall A', 38000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(702, 'Taekwondo', 'Women -49kg', 'FEB-19-2020', 'Makuhari Messe Hall A', 38000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(703, 'Taekwondo', 'Women -57kg', 'FEB-19-2020', 'Makuhari Messe Hall A', 38000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(704, 'Taekwondo', 'Women -67kg', 'FEB-19-2020', 'Makuhari Messe Hall A', 38000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(705, 'Taekwondo', 'Women +67kg', 'FEB-19-2020', 'Makuhari Messe Hall A', 38000);

INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(706, 'Tennis', 'Singles (Men)', 'JUL-28-2021', 'Ariake Tennis Park Centre Court', 55000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(707, 'Tennis', 'Singles (Women)', 'JUL-29-2021', 'Ariake Tennis Park Centre Court', 55000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(708, 'Tennis', 'Doubles (Men)', 'JUL-30-2021', 'Ariake Tennis Park Centre Court', 55000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(709, 'Tennis', 'Doubles (Women)', 'JUL-30-2021', 'Ariake Tennis Park Centre Court', 55000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(710, 'Tennis', 'Mixed Doubles', 'JUL-31-2021', 'Ariake Tennis Park Centre Court', 55000);

INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(711, 'Trampoline Gymnastics', 'Individual competition (Men)', 'FEB-18-2020', 'Ariake Gymnastics Centre', 33000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(712, 'Trampoline Gymnastics', 'Individual competition (Women)', 'JUL-30-2021', 'Ariake Gymnastics Centre', 33000);

INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(713, 'Triathlon', 'PTWC (Men)', 'FEB-21-2020', 'Odaiba Marine Park', 40000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(714, 'Triathlon', 'PTWC (Women)', 'FEB-21-2020', 'Odaiba Marine Park', 40000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(715, 'Triathlon', 'PTS2 (Women)', 'FEB-21-2020', 'Odaiba Marine Park', 40000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(716, 'Triathlon', 'PTS4 (Men)', 'FEB-21-2020', 'Odaiba Marine Park', 40000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(717, 'Triathlon', 'PTS5 (Men)', 'FEB-21-2020', 'Odaiba Marine Park', 40000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(718, 'Triathlon', 'PTS5 (Women)', 'FEB-21-2020', 'Odaiba Marine Park', 40000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(719, 'Triathlon', 'PTVI (Men)', 'AUG-28-2021', 'Odaiba Marine Park', 40000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(720, 'Triathlon', 'PTVI (Women)', 'AUG-28-2021', 'Odaiba Marine Park', 40000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(721, 'Triathlon', 'PTS4 (Men): including PTS2 & PTS3', 'AUG-28-2021', 'Odaiba Marine Park', 40000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(722, 'Triathlon', 'PTS5 (Women): including PTS3 & PTS4', 'AUG-29-2021', 'Odaiba Marine Park', 40000);

INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(723, 'Volleyball', '12-team tournament (Men)', 'AUG-04-2021', 'Ariake Arena', 72000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(724, 'Volleyball', '12-team tournament (Women)', 'AUG-07-2021', 'Ariake Arena', 72000);

INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(725, 'Water Polo', '12-team tournament (Men)', 'AUG-04-2021', 'Tatsumi Water Polo Centre', 44000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(726, 'Water Polo', '10-team tournament (Women)', 'AUG-06-2021', 'Tatsumi Water Polo Centre', 44000);

INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(727, 'Weightlifting', '61kg (Men)', 'JUL-31-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(728, 'Weightlifting', '67kg (Men)', 'JUL-31-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT (EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET)VALUES(729, 'Weightlifting', '73kg (Men)', 'JUL-31-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(730, 'Weightlifting', '81kg (Men)', 'AUG-01-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(731, 'Weightlifting', '96kg (Men)', 'AUG-01-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(732, 'Weightlifting', '109kg (Men', 'AUG-01-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(733, 'Weightlifting', '+109kg (Men)', 'AUG-02-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(734, 'Weightlifting', '49kg (Women)', 'AUG-02-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(735, 'Weightlifting', '55kg (Women)', 'AUG-02-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(736, 'Weightlifting', '59kg (Women)', 'AUG-03-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(737, 'Weightlifting', '64kg (Women)', 'AUG-03-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(738, 'Weightlifting', '76kg (Women)', 'AUG-03-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(739, 'Weightlifting', '87kg (Women)', 'AUG-04-2021', 'Tokyo International Forum', 50000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(740, 'Weightlifting', '+87kg (Women)', 'AUG-04-2021', 'Tokyo International Forum', 50000);


INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(741, 'Wrestling', 'Freestyle (Men) ', 'AUG-03-2021', 'Makuhari Messe Hall A Mat A', 48000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(742, 'Wrestling', 'Freestyle (Women) ', 'AUG-03-2021', 'Makuhari Messe Hall A Mat A', 48000);

INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(743, 'Wrestling', 'Greco-Roman (Men) ', 'AUG-04-2021', 'Makuhari Messe Hall A Mat A', 48000);
INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DATE,LOCATION,BUDGET) VALUES(744, 'Wrestling', 'Greco-Roman (Women) ', 'AUG-05-2021', 'Makuhari Messe Hall A Mat A', 48000);

--INSERT INTO NEWSANDVIDEOS VALUES(2000, 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2000,'https://www.youtube.com/watch?v=9bd-De6lJHY ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2001,'https://www.youtube.com/watch?v=LcdkaMFgBLw ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2002,'https://www.youtube.com/watch?v=1DuxtNsH3Lw ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2003,'https://www.youtube.com/watch?v=LUdW2Eh7ASM ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2004,'https://www.youtube.com/watch?v=Tb7edAcANaw ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2005,'https://www.youtube.com/watch?v=qe4uifT7kug ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2006,'https://www.youtube.com/watch?v=k_-aNFeYPuc ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2007,'https://www.youtube.com/watch?v=8YSrNfcKvA0 ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2008,'https://www.youtube.com/watch?v=7FeXLs9JdSE ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2009,'https://www.youtube.com/watch?v=tfbm4TQdw1w ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2010,'https://www.youtube.com/watch?v=qr9F8yBLIkA ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2011,'https://www.youtube.com/watch?v=AkMMIYnRqlY ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2012,'https://www.youtube.com/watch?v=PU4Oo-NnBZ0 ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2013,'https://www.youtube.com/watch?v=Peqgm7w6s-c ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2014,'https://www.youtube.com/watch?v=Ri5VKDMx04o ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2015,'https://www.youtube.com/watch?v=TNeCS5iXQK4 ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2016,'https://www.youtube.com/watch?v=T0HuNK_Bvms ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2017,'https://www.youtube.com/watch?v=Dn8-M2zW9PU ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2018,'https://www.youtube.com/watch?v=yRbv1Ct_BPc ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2019,'https://www.youtube.com/watch?v=PjJowFMZ3oc ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2020,'https://www.youtube.com/watch?v=KbBwXCqLoZo ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2021,'https://www.youtube.com/watch?v=kVLJCWlz7jw ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2022,'https://www.youtube.com/watch?v=KbBwXCqLoZo&t=23s ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2023,'https://www.youtube.com/watch?v=6_5I2h_jpO0 ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2024,'https://www.youtube.com/watch?v=mnoJ7XdD7XU ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2025,'https://www.youtube.com/watch?v=-23vCuJps8c ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2026,'https://www.youtube.com/watch?v=nPcg3cKi5OY ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2027,'https://www.youtube.com/watch?v=7KWvFfHok2Q ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2028,'https://www.youtube.com/watch?v=UdaLsdO5zSU ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2029,'https://www.youtube.com/watch?v=FZy3lEDYkds ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2030,'https://www.youtube.com/watch?v=e-w8RtD6cjA ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2031,'https://www.youtube.com/watch?v=27j7ZcGl0Ls ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2032,'https://www.youtube.com/watch?v=1qyZidUllxE ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2033,'https://www.youtube.com/watch?v=zwXp8lmeUuA ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2034,'https://www.youtube.com/watch?v=TnwR3C3Rgzg ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2035,'https://www.youtube.com/watch?v=k0CWpgem8gQ ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2036,'https://www.youtube.com/watch?v=p4N1jaCAB3U ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2037,'https://www.youtube.com/watch?v=N-QW3yV-GWk ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2038,'https://www.youtube.com/watch?v=Mv_p2yu6Oaw ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2039,'https://www.youtube.com/watch?v=T9CGWJ2bSl4 ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2040,'https://www.youtube.com/watch?v=IRYPtGP2FGI ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2041,'https://www.youtube.com/watch?v=wzSbQNB4NtA ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2042,'https://www.youtube.com/watch?v=2ruvu8kZyOk ', 'Must use intellectual property');
INSERT INTO NEWSANDVIDEOS(NEWS_ID, NEWS_LINK, COPYRIGHT) VALUES(2043,'https://www.youtube.com/watch?v=6eZie7l8gVw ', 'Must use intellectual property');


--INSERT INTO EVENT_NEWS VALUES(20, 2000, 'JUN-03-2020', 'Made 10 points in  a row');
INSERT INTO EVENT_NEWS VALUES(500, 2000, 'JUl-03-2021', 'The USA posted a 6-1 record in the pool stage, topping the table with a 19.4 points per game average.');
INSERT INTO EVENT_NEWS VALUES(501, 2001, 'AUG-26-2021', 'Made 10 points in  a row');
INSERT INTO EVENT_NEWS VALUES(504, 2002, 'AUG-16-2021', 'Five years on, and now 24, Biles has been making headlines around the world.');
INSERT INTO EVENT_NEWS VALUES(515, 2003, 'AUG-04-2021', 'Twenty-one-time world champion Svetlana Romashina is now a six-time Olympic champion.');
INSERT INTO EVENT_NEWS VALUES(517, 2004, 'AUG-10-2021', 'In Tokyo, Felix ran the 400 in a blazing 49.46, the second fastest time in her 17-year career.');
INSERT INTO EVENT_NEWS VALUES(531, 2005, 'AUG-03-2021', 'Olympics Badminton Gold Winner Viktor Axelsen Swaps Shirt With Opponent.');
INSERT INTO EVENT_NEWS VALUES(536, 2006, 'JUl-28-2021', 'Late comeback keeps Japanese party going after softball success');
INSERT INTO EVENT_NEWS VALUES(537, 2007, 'AUG-08-2021', 'Prior to Tokyo 2020, the Japanese womens teams best result at an Olympic Games was a fifth-place back in 1976 in Montreal.');
INSERT INTO EVENT_NEWS VALUES(539, 2008, 'AUG-05-2021', 'Switzerlands Nina Betschart and Tanja Huberli (right) talk strategy during their match.');
INSERT INTO EVENT_NEWS VALUES(541, 2009, 'JUl-24-2021', 'Julio Cesar La Cruz of Cuba (right) strikes at Muslim Gadzhimagomedov of the Russian Olympic Committee Pool during the 2020 Tokyo Olympic Games.');
INSERT INTO EVENT_NEWS VALUES(554, 2010, 'JUN-03-2020', 'Five years ago Funk, now 29, was not even selected for the team in Rio, now she is an Olympic champion.');
INSERT INTO EVENT_NEWS VALUES(566, 2011, 'JUl-31-2021', ' The Thomson Reuters Trust Principles.');
INSERT INTO EVENT_NEWS VALUES(569, 2012, 'JUl-24-2021', 'The Ecuadorian rider broke away with six kilometres left of the 234km-long race to win in 6:05.26.');
INSERT INTO EVENT_NEWS VALUES(571, 2013, 'AUG-16-2021', 'Great Britain, a formidable powerhouse in track cycling, maintained its steady grip on the sport medalling in seven of the 12 events.');
INSERT INTO EVENT_NEWS VALUES(577, 2014, 'AUG-06-2021', 'From Tom Daley to Simone Biles, these heroes have made the 2020 Tokyo Olympics.');
INSERT INTO EVENT_NEWS VALUES(581, 2015, 'JUl-29-2021', 'Eventing first horse inspection - 01.30–03.30');
INSERT INTO EVENT_NEWS VALUES(584, 2016, 'AUG-31-2021', 'From Áron Szilágyis threepeat to Lee Kiefers maiden gold for USA, fencing lit up the Tokyo 2020 Olympic Games.');
INSERT INTO EVENT_NEWS VALUES(590, 2017, 'AUG-12-2021', ' Brazil came up as the champions ultimately, but it did not look to be as certain from the beginning.');
INSERT INTO EVENT_NEWS VALUES(594, 2018, 'AUG-07-2021', 'From a Nelly Korda/Xander Schauffele USA double to a seven-man playoff for bronze, golf lit up the Tokyo 2020 Olympic Games.');
INSERT INTO EVENT_NEWS VALUES(598, 2019, 'AUG-05-2021', 'The Indian mens hockey team beat Germany 5-4 to win the bronze medal playoff to end the 41-year wait for the podium.');
INSERT INTO EVENT_NEWS VALUES(600, 2020, 'JUl-31-2021', 'Abe Uta was first, coming through an epic women’s -52kg final with Amandine Buchard.');
INSERT INTO EVENT_NEWS VALUES(615, 2021, 'AUG-31-2021', 'Feryal Abdelaziz stunned the world to become the first Egyptian woman to win a gold medal at the Olympic Games, upsetting World No.1 Iryna Zaretska of Azerbaijan.');
INSERT INTO EVENT_NEWS VALUES(621, 2022, 'AUG-18-2021', 'The relief on Ana Marcela Cunha’s face when she won the women’s marathon swimming gold medal was palpable');
INSERT INTO EVENT_NEWS VALUES(627, 2023, 'JUl-24-2021', 'Sara Bertolasi, 30 years old, two Olympic Games on her belt');
INSERT INTO EVENT_NEWS VALUES(641, 2024, 'AUG-09-2021', 'There was plenty of pre-tournament hype, with many of the world’s top 15-a-side players like Portia Woodman, Semi Radradra and Samu Kerevi signing up for a crack at Olympic gold.');
INSERT INTO EVENT_NEWS VALUES(643, 2025, 'AUG-04-2021', 'reat Britains Hannah Mills became the most decorated female Olympic sailor in history after she successfully defended her 470 title alongside Eilidh McIntyre in Japan.');
INSERT INTO EVENT_NEWS VALUES(653, 2026, 'JUl-27-2021', '21-year-old Yang claimed gold in the 10 metre air rifle event  setting a new Olympic record.');
INSERT INTO EVENT_NEWS VALUES(675, 2027, 'JUl-28-2021', 'From Ariarne Titmus freestyle heroics to Caeleb Dressels world record.');
INSERT INTO EVENT_NEWS VALUES(693, 2028, 'AUG-06-2021', 'From 12-year-old Hend Zaza to 58-year-old NI Xia Lian, table tennis was at its hypnotic best at the Tokyo 2020 Olympic Games.');
INSERT INTO EVENT_NEWS VALUES(698, 2029, 'JUl-25-2021', 'From teenagers Ulugbek Rashitov and Anastasija Zolotics upset victories to capture gold.');
INSERT INTO EVENT_NEWS VALUES(713, 2030, 'JUl-31-2021', 'From Flora Duffy giving Bermuda a maiden gold to the first ever Olympic mixed relay');
INSERT INTO EVENT_NEWS VALUES(727, 2031, 'JUl-06-2021', 'China was the dominant nation in weightlifting,winning five golds');
INSERT INTO EVENT_NEWS VALUES(741, 2032, 'AUG-03-2021', 'At Tokyo 2020, 96 men in each style and 96 women will compete in the wrestling competition.');

--INSERT INTO COUNTRIES VALUES('BD', 'Bangladesh', 'Asia');
-----------------------(Asia Block)-----------------------
----------------------------------------------------------
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('BD', 'Bangladesh', 'Asia');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('CN', 'China', 'Asia');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('IN', 'India', 'Asia');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('ID', 'Indonasia', 'Asia');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('JP', 'Japan', 'Asia');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('MY', 'Malaysia', 'Asia');       
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('PK', 'Pakistan', 'Asia');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('PH', 'Philippines', 'Asia');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('KR', 'South Korea', 'Asia');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('TH', 'Thailand', 'Asia');


----------------------(Africa Block)----------------------
----------------------------------------------------------
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('BW', 'Botswana', 'Africa');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('CI', 'Côte dIvoire', 'Africa');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('EG', 'Egypt', 'Africa');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('ET', 'Ethiopia', 'Africa');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('GH', 'Ghana', 'Africa');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('KE', 'Kenya', 'Africa');      
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('MA', 'Morocco', 'Africa');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('NG', 'Nigeria', 'Africa');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('ZA', 'South Africa', 'Africa');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('UG', 'Uganda', 'Africa');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('AU', 'Australia', 'Australia');

-----------------------(Europe Block)-----------------------
------------------------------------------------------------
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('AT', 'Austria', 'Europe');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('BE', 'Belgium', 'Europe');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('CZ', 'Czech Republic', 'Europe');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('DK', 'Denmark', 'Europe');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('FR', 'France', 'Europe');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('DE', 'Germany', 'Europe');      
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('HU', 'Hungary', 'Europe');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('IT', 'Italy', 'Europe');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('RU', 'Russian Federation', 'Europe');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('GB', 'United Kingdom', 'Europe');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('SE', 'Sweden', 'Europe');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('ES', 'Spain', 'Europe');

-----------------------(North America Block)-----------------------
-------------------------------------------------------------------
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('BS', 'Bahamas', 'North America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('CA', 'Canada', 'North America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('CR', 'Costa Rica', 'North America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('SV', 'El Salvador', 'North America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('JM', 'Jamaica', 'North America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('MX', 'Mexico', 'North America');        
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('PA', 'Panama', 'North America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('PR', 'Puerto Rico', 'North America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('LC', 'Saint Lucia', 'North America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('US', 'United States America', 'North America');

----------------------(South America Block)------------------------
-------------------------------------------------------------------
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('AR', 'Argentina', 'South America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('BO', 'Bolivia', 'South America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('BR', 'Brazil', 'South America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('CO', 'Colombia', 'South America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('EC', 'Ecuador', 'South America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('PY', 'Paraguay', 'South America');        
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('PE', 'Peru', 'South America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('SR', 'Suriname', 'South America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('UY', 'Uruguay', 'South America');
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION) VALUES ('VE', 'Venezuela', 'South America');

--INSERT INTO COACH VALUES(10, 'Alice', 'Mark', 'BD', 5);
----------------------(Asia Block)----------------------
--------------------------------------------------------
INSERT INTO COACH VALUES (50, 'Megan', 'Dean','SE', 5);
INSERT INTO COACH VALUES (51, 'Lindsey', 'Powell','AU', 6);
INSERT INTO COACH VALUES (52, 'Tara', 'Brooks','HU', 7);
INSERT INTO COACH VALUES (53, 'Kayla ', 'Pearson','CN', 8);
INSERT INTO COACH VALUES (54, 'Randall', 'Byrd','IT', 6);
INSERT INTO COACH VALUES (55, 'Timothy', 'Dixon','GB', 5);    
INSERT INTO COACH VALUES (56, 'Jessica', 'Gilbert','FR', 9);
INSERT INTO COACH VALUES (57, 'Carolyn', 'Andrews','DE', 4);
INSERT INTO COACH VALUES (58, 'Lauren', 'Scott','RU', 2);
INSERT INTO COACH VALUES (59, 'Pamela', 'Dillon','US', 6);

---------------------(Africa Block)---------------------
--------------------------------------------------------
INSERT INTO COACH VALUES (60, 'Heather', 'Evans', 'US', 3);
INSERT INTO COACH VALUES (61, 'Kelly', 'Reilly', 'US', 9);
INSERT INTO COACH VALUES (62, 'Rachel', 'Miller', 'DE', 8);
INSERT INTO COACH VALUES (63, 'William', 'Meyers', 'DE', 7);
INSERT INTO COACH VALUES (64, 'Scott', 'Lee', 'GB', 5);    
INSERT INTO COACH VALUES (65, 'Amy', 'Black', 'GB', 4);
INSERT INTO COACH VALUES (66, 'Scott', 'Kung', 'CN', 6);
INSERT INTO COACH VALUES (67, 'William', 'Wong', 'CN', 3);
INSERT INTO COACH VALUES (68, 'Tyrone', 'Duncan', 'AU', 2);
INSERT INTO COACH VALUES (69, 'David', 'Lewis', 'AU', 2);

---------------------(Europe Block)---------------------
--------------------------------------------------------
INSERT INTO COACH VALUES (70, 'Emily', 'Jenkins', 'US', 8);
INSERT INTO COACH VALUES (71, 'Francis', 'Cook', 'RU', 7);
INSERT INTO COACH VALUES (72, 'Robert', 'Mccarthy', 'DE', 5);
INSERT INTO COACH VALUES (73, 'Nicole', 'Brennan', 'FR', 4);
INSERT INTO COACH VALUES (74, 'Justin', 'Beltran', 'GB', 9);
INSERT INTO COACH VALUES (75, 'Mike', 'Richards', 'IT', 6);      
INSERT INTO COACH VALUES (76, 'Susan', 'Xiang', 'CN', 4);
INSERT INTO COACH VALUES (77, 'Kelly', 'Doyle', 'HU', 5);
INSERT INTO COACH VALUES (78, 'Steven', 'Evans', 'RU', 7);
INSERT INTO COACH VALUES (79, 'Elizabeth', 'Cook', 'SE', 3);

-----------------(North America Block)------------------
--------------------------------------------------------
INSERT INTO COACH VALUES (80, 'Bruce', 'Acosta', 'IT', 3);
INSERT INTO COACH VALUES (81, 'Monica', 'Mathews', 'IT', 2);
INSERT INTO COACH VALUES (82, 'Amanda', 'Little', 'IT', 3);
INSERT INTO COACH VALUES (83, 'Jennifer', 'Walters', 'FR', 4);
INSERT INTO COACH VALUES (84, 'Miranda', 'Graham', 'FR', 5);       
INSERT INTO COACH VALUES (85, 'Ryan', 'Case', 'FR', 6);
INSERT INTO COACH VALUES (86, 'Patricia', 'Ferrell', 'DE', 7);
INSERT INTO COACH VALUES (87, 'Dorothy', 'Johnson', 'DE', 8);
INSERT INTO COACH VALUES (88, 'Justin', 'Hamilton', 'US', 9);
INSERT INTO COACH VALUES (89, 'Joel', 'Abbott', 'US', 5);

-----------------(South America Block)------------------
--------------------------------------------------------
INSERT INTO COACH VALUES (90, 'Stacey', 'Hartman', 'US', 3);
INSERT INTO COACH VALUES (91, 'Craig','Brewer', 'US', 4);
INSERT INTO COACH VALUES (92, 'Crystal', 'Bryant', 'US', 5);
INSERT INTO COACH VALUES (93, 'Nicholas', 'Nicholas', 'GB', 6);
INSERT INTO COACH VALUES (94, 'Sarah','Carpenter', 'GB', 7);         
INSERT INTO COACH VALUES (95, 'Nicholas', 'Johnson', 'RU', 9);
INSERT INTO COACH VALUES (96, 'Anne', ' Sandoval', 'RU', 1);
INSERT INTO COACH VALUES (97, 'Alyssa','Baxter', 'RU', 4);
INSERT INTO COACH VALUES (98, 'Ashley', 'Thomas', 'RU', 6);
INSERT INTO COACH VALUES (99, 'James','Peterson', 'RU', 8);

--INSERT INTO TEAMS VALUES(1500, 'BD', 20, 10);
-----------------(Asia Block)-----------------
----------------------------------------------
INSERT INTO TEAMS VALUES (1501, 'BD', 500, 50);
INSERT INTO TEAMS VALUES (1502, 'CN', 501, 51);
INSERT INTO TEAMS VALUES (1503, 'IN', 502, 52);
INSERT INTO TEAMS VALUES (1504, 'ID', 503, 53);
INSERT INTO TEAMS VALUES (1505, 'JP', 504, 54);
INSERT INTO TEAMS VALUES (1506, 'MY', 505, 55);            
INSERT INTO TEAMS VALUES (1507, 'PK', 506, 56);
INSERT INTO TEAMS VALUES (1508, 'PH', 507, 57);
INSERT INTO TEAMS VALUES (1509, 'KR', 508, 58);
INSERT INTO TEAMS VALUES (1510, 'TH', 509, 59);

---------------(Africa Block)-----------------
----------------------------------------------
INSERT INTO TEAMS VALUES (1511, 'BW', 510, 60);
INSERT INTO TEAMS VALUES (1512, 'CI', 511, 61);
INSERT INTO TEAMS VALUES (1513, 'EG', 512, 62);
INSERT INTO TEAMS VALUES (1514, 'ET', 513, 63);
INSERT INTO TEAMS VALUES (1515, 'GH', 514, 64);            
INSERT INTO TEAMS VALUES (1516, 'KE', 515, 65);
INSERT INTO TEAMS VALUES (1517, 'MA', 516, 66);
INSERT INTO TEAMS VALUES (1518, 'NG', 517, 67);
INSERT INTO TEAMS VALUES (1519, 'ZA', 518, 68);
INSERT INTO TEAMS VALUES (1520, 'UG', 519, 69);

----------------(Europe Block)----------------
----------------------------------------------
INSERT INTO TEAMS VALUES (1521, 'AT', 520, 70);
INSERT INTO TEAMS VALUES (1522, 'BE', 521, 71);
INSERT INTO TEAMS VALUES (1523, 'CZ', 522, 72);
INSERT INTO TEAMS VALUES (1524, 'DK', 523, 73);
INSERT INTO TEAMS VALUES (1525, 'FR', 524, 74);
INSERT INTO TEAMS VALUES (1526, 'DE', 525, 75);            
INSERT INTO TEAMS VALUES (1527, 'HU', 526, 76);
INSERT INTO TEAMS VALUES (1528, 'IT', 527, 77);
INSERT INTO TEAMS VALUES (1529, 'RU', 528, 78);
INSERT INTO TEAMS VALUES (1530, 'GB', 529, 79);

------------(North America Block)-------------
----------------------------------------------
INSERT INTO TEAMS VALUES (1531, 'BS', 530, 80);
INSERT INTO TEAMS VALUES (1532, 'CA', 531, 81);
INSERT INTO TEAMS VALUES (1533, 'CR', 532, 82);
INSERT INTO TEAMS VALUES (1534, 'SV', 533, 83);
INSERT INTO TEAMS VALUES (1535, 'JM', 534, 84);
INSERT INTO TEAMS VALUES (1536, 'MX', 535, 85);          
INSERT INTO TEAMS VALUES (1537, 'PA', 536, 86);
INSERT INTO TEAMS VALUES (1538, 'PR', 537, 87);
INSERT INTO TEAMS VALUES (1539, 'LC', 538, 88);
INSERT INTO TEAMS VALUES (1540, 'US', 539, 89);

------------(South America Block)-------------
----------------------------------------------
INSERT INTO TEAMS VALUES (1541, 'AR', 540, 90);
INSERT INTO TEAMS VALUES (1542, 'BO', 541, 91);
INSERT INTO TEAMS VALUES (1543, 'BR', 542, 92);
INSERT INTO TEAMS VALUES (1544, 'CO', 543, 93);
INSERT INTO TEAMS VALUES (1545, 'EC', 544, 94);
INSERT INTO TEAMS VALUES (1546, 'PY', 545, 95);            
INSERT INTO TEAMS VALUES (1547, 'PE', 546, 96);
INSERT INTO TEAMS VALUES (1548, 'SR', 547, 97);
INSERT INTO TEAMS VALUES (1549, 'UY', 548, 98);
INSERT INTO TEAMS VALUES (1550, 'VE', 549, 99);

--INSERT INTO ATHLETE VALUES(01, 'Shahadat', 'Anik', 21, 5.7, 60.5, 'M', 'N', 'BD', 10, 20, 1500, 200.5, 2);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (01, 'ABAD','Nestor', 23, 6.1, 55.5, 'M', 'N', 'ES', 505, 50, 23.0, 10);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (02, 'ABALDE','Tamara', 21, 5.11, 60.5, 'F', 'N', 'ES', 538, 51, 6.0, 20);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (03, 'ACHANTA','Kamal', 37, 6.1, 57.5, 'M', 'N', 'IN',  693, 52, 32.0, 32);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (04, 'BADOSA ','Paula', 23, 6.1, 54.5, 'F', 'N', 'ES',  694, 53, 37.0, 30);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (05, 'BAE','Hyeyoon', 25, 5.11, 58.5, 'F', 'N', 'KR', 538, 54, 29.0, 24);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (06, 'BALOGUN','Elizabeth', 30, 6.1, 58.5, 'F', 'N', 'NG', 538, 55, 3.0, 12);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (07, 'BARNES','David', 22, 5.11, 59.5, 'M', 'N', 'AU', 501, 56, 34.0, 15);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (08, 'BARRETT','Stephanie', 34, 6.1, 62.5, 'M', 'N', 'CA', 501, 57, 20.0, 25.4);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (09, 'BASSETO ','Guilherme', 32, 6.4, 65.5, 'M', 'N', 'BR', 675, 58, 8.0, 19);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (10, 'BEKESI','Eszter', 28, 5.10, 62.5, 'M', 'N', 'HU', 667, 59, 2.0, 16);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (11, 'BJERENDAL','Christine', 23, 6.1, 55.5, 'M', 'N', 'SE', 501, 61, 25.0, 11);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (12, 'CASTRO','Daniel', 26, 6.6, 67.5, 'M', 'N', 'ES', 501, 63, 12.0, 20);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (13, 'CELIS','Nick', 32, 6.3, 60.5, 'M', 'N', 'BE', 537, 67,  15.0, 13.7);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (14, 'CHARLES ','Tina', 25, 6.1, 54.5, 'F', 'N', 'US', 538, 70, 18.0, 38);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (15, 'CHELANGAT','Sarah', 34, 6.2, 52.5, 'F', 'N', 'UG', 517, 76, 20.0, 43);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (16, 'CHELIMO','Oscar', 24, 6.1, 60.5, 'M', 'N', 'UG', 523, 82, 17.0, 16);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (17, 'CHEN','Long', 24, 6.1, 55.5, 'M', 'N', 'CN', 531, 66, 36.0, 48);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (18, 'CHEW','Phillip', 21, 5.10, 59.5, 'M', 'N', 'CN', 533, 89, 38.0, 49);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (19, 'DARSIGNY','Tali', 34, 6.2, 64.5, 'M', 'N', 'CA', 727, 81, 48.0, 38);
INSERT INTO ATHLETE (ATHLETE_ID, FIRST_NAME,LAST_NAME,AGE,HEIGHT,WEIGHT,GENDER,MARITIAL_STATUS,COUNTRY_ID,EVENT_ID,COACH_ID,RANK_POINT,COACHING_DURATION) VALUES (20, 'LI','Wenwen', 33, 6.1, 64.5, 'M', 'N', 'CN', 727,  90, 28.0, 29);

--INSERT INTO FANZONE VALUES(1001, 'Dil', 'Nur', 15, 'BD');
INSERT INTO FANZONE VALUES (1001, 'CLERK', 'KENT', 20, 'BR');
INSERT INTO FANZONE VALUES (1002, 'JONATHON', 'KENT', 20, 'AU');
INSERT INTO FANZONE VALUES (1003, 'MARTHA', 'KENT', 22, 'CA');
INSERT INTO FANZONE VALUES (1004, 'TONY', 'HANK', 30, 'US');
INSERT INTO FANZONE VALUES (1005, 'WALTER', 'WHITE', 25, 'US');
INSERT INTO FANZONE VALUES (1006, 'PETER', 'PARKER', 20, 'CN');
INSERT INTO FANZONE VALUES (1007, 'STEVE', 'ROGERS', 24, 'BR');
INSERT INTO FANZONE VALUES (1008, 'BARRY', 'ALLEN', 18, 'UG');
INSERT INTO FANZONE VALUES (1010, 'PEPPER', 'POTTS', 16, 'CA');
INSERT INTO FANZONE VALUES (1011, 'KAL', 'EL', 18, 'SE');
INSERT INTO FANZONE VALUES (1012, 'THANOS', 'STARK', 10, 'SE');
INSERT INTO FANZONE VALUES (1013, 'GAMORA', 'QUIL', 13, 'ES');
INSERT INTO FANZONE VALUES (1014, 'EMMA', 'STONE', 29, 'AR');
INSERT INTO FANZONE VALUES (1015, 'TOBE', 'MAGUAR', 24, 'BD');
INSERT INTO FANZONE VALUES (1016, 'HENRY', 'CAVIL', 27, 'BD');
INSERT INTO FANZONE VALUES (1017, 'BRUCE', 'WAYNE', 23, 'ES');
INSERT INTO FANZONE VALUES (1018, 'LOUIS', 'LANE', 22, 'ES');
INSERT INTO FANZONE VALUES (1019, 'DIANA', 'PRINCE', 14, 'AR');
INSERT INTO FANZONE VALUES (1020, 'NAT', 'ROMAN', 19, 'AU');
INSERT INTO FANZONE VALUES (1021, 'CLINT', 'BURTON', 21, 'AU');

--INSERT INTO ATHLETE_FANZONE VALUES(01, 1001, 'MAY-05-2019');
INSERT INTO ATHLETE_FANZONE VALUES(01,1001,'MAY-05-2019');
INSERT INTO ATHLETE_FANZONE VALUES(02,1002,'JUN-10-2019');
INSERT INTO ATHLETE_FANZONE VALUES(03,1003,'APR-03-2019');
INSERT INTO ATHLETE_FANZONE VALUES(04,1004,'MAR-02-2019');
INSERT INTO ATHLETE_FANZONE VALUES(05,1005,'JAN-24-2020');
INSERT INTO ATHLETE_FANZONE VALUES(06,1006,'APR-10-2020');
INSERT INTO ATHLETE_FANZONE VALUES(07,1007,'FEB-26-2018');
INSERT INTO ATHLETE_FANZONE VALUES(08,1008,'APR-17-2020');
INSERT INTO ATHLETE_FANZONE VALUES(09,1009,'MAY-12-2018');
INSERT INTO ATHLETE_FANZONE VALUES(10,1010,'AUG-11-2019');
INSERT INTO ATHLETE_FANZONE VALUES(11,1011,'AUG-19-2018');
INSERT INTO ATHLETE_FANZONE VALUES(12,1012,'OCT-02-2020');
INSERT INTO ATHLETE_FANZONE VALUES(13,1013,'DEC-09-2019');
INSERT INTO ATHLETE_FANZONE VALUES(14,1014,'DEC-20-2017');
INSERT INTO ATHLETE_FANZONE VALUES(15,1015,'JAN-19-2017');
INSERT INTO ATHLETE_FANZONE VALUES(16,1016,'MAY-08-2019');
INSERT INTO ATHLETE_FANZONE VALUES(17,1017,'FEB-26-2020');
INSERT INTO ATHLETE_FANZONE VALUES(18,1018,'AUG-04-2019');
INSERT INTO ATHLETE_FANZONE VALUES(19,1019,'JUN-01-2020');
INSERT INTO ATHLETE_FANZONE VALUES(20,1020,'APR-05-2018');

--INSERT INTO MEDALS VALUES(01, 'Silver');
INSERT INTO MEDALS VALUES (01,'GOLD');
INSERT INTO MEDALS VALUES (02,'SILVER');
INSERT INTO MEDALS VALUES (03,'GOLD');
INSERT INTO MEDALS VALUES (04,'GOLD');
INSERT INTO MEDALS VALUES (05,'BRONZE');
INSERT INTO MEDALS VALUES (06,'SILVER');
INSERT INTO MEDALS VALUES (07,'BRONZE');
INSERT INTO MEDALS VALUES (08,'GOLD');
INSERT INTO MEDALS VALUES (09,'SILVER');
INSERT INTO MEDALS VALUES (10,'SILVER');
INSERT INTO MEDALS VALUES (11,'GOLD');
INSERT INTO MEDALS VALUES (12,'BRONZE');
INSERT INTO MEDALS VALUES (13,'SILVER');
INSERT INTO MEDALS VALUES (14,'BRONZE');
INSERT INTO MEDALS VALUES (15,'SILVER');
INSERT INTO MEDALS VALUES (16,'SILVER');
INSERT INTO MEDALS VALUES (17,'GOLD');
INSERT INTO MEDALS VALUES (18,'BRONZE');
INSERT INTO MEDALS VALUES (19,'SILVER');
INSERT INTO MEDALS VALUES (20,'GOLD');

